version: "3.8"

services:

  order_service:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SERVICE_TYPE=api
    depends_on:
      - db_orders
      - redis
      - rabbitmq

  celery_worker:
    build: .
    command: >
      sh -c "celery -A app.domain.services.tasks.celery_worker worker --loglevel=info"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - SERVICE_TYPE=worker
    depends_on:
      - rabbitmq
      - redis
      - db_orders

  flower:
    build: .
    command: >
      sh -c "celery -A app.domain.services.tasks.celery_worker flower --port=5555"
    ports:
      - "5555:5555"
    env_file:
      - .env
    environment:
      - SERVICE_TYPE=flower
    depends_on:
      - celery_worker
      - rabbitmq

  db_orders:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

volumes:
  postgres_data:
